name: CI
run-name: ${{ github.actor }} push | ${{ github.ref }}

on: push
jobs:
  build:
    runs-on: ubuntu-latest #a machine running latest version of ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3 #checkout the current repository and push the files to the machine
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD   
      - name: build docker image
        run: docker build . -t xqsmog/testimages:latest2
      - name: Docker Push
        run: docker push xqsmog/testimages
